### ISSUE TITLE
Create Dockerfile for an easy deploy

### ISSUE THREAD

**Issue by edoz90** [Volmarg/personal-management-system#12]
Hi!

Do you plan to create a Dockerfile for the application?

**Comment by Volmarg** [comment]
Hi, no. 
The only thing I plan is maybe an **ant** script or some automated section in composer. It will just basically call all the commands, download packages, rebuild files, set configurations etc. So by typing one command everything should be working.

**Comment by Volmarg** [comment]
Update.

I've made an autoinstaller script **For linux** it won't do everything for You, but will show You what important packages are missing in the installation, what You have to provide (interactive cli) etc. 

There are still some things that must be edited, installed manually - but there is not much I can do about it so I'm not touching part like "changing mysql conf" because editing it via commands might mess it up, also the conf file might be in totally custom location if You got some different configuration/version.

What You got to do is calling in project root `composer install`, and on the end You will see the installer (if all the packages from composer are installed then it will go automatically to the project 
 installation part).

I'm not doing the docker deployment so You need to handle with this installer - feel free to raise any issues related to it or the installation process itself.

**Comment by EduardoOliveira** [comment]
Hi, sorry for the reopen, but would you consider a pull request to implement a docker container, and possible automation to rebuild the image on push to this repo?

**Comment by Volmarg** [comment]
Hey,

I'm not planning it.
The thing is that I hadn't played with Docker for over 1.5 year.
2nd thing It's just waste of time for me to relearn some things.

If You have so magicall dunno 20 commands to call or something they I could call it and push that - whatever there is expected on output but otherwise that's not happening.
