### ISSUE TITLE
CRITICAL Severity Security Vulnerability

### ISSUE THREAD

**Issue by rudransh02** [Volmarg/personal-management-system#144]
Hey Dariusz,

I hope this message finds you well.

I am Rudransh Singh Rajpurohit, a Cyber Security Researcher.

While reviewing your project, I identified two potential security vulnerabilities, for which I have reached out to MITRE to get CVEs assigned to them but they are in reserved state as of now:

1. CVE-2024-53568: Stored Cross-Site Scripting (XSS) in the Image Upload section.
2. CVE-2024-53569: Stored Cross-Site Scripting (XSS) in the New Goal Creation section.

To ensure responsible disclosure, I would like to share more details about these vulnerabilities privately. Please let me know the best email address to reach you. Once you deploy the necessary fixes on production, I would be making these public so that MITRE could be able to publicly publish these CVEs.

Looking forward to your response.

Best Regards,
**Rudransh Singh Rajpurohit | CEH, CAP, CNSP
Cyber Security Researcher
Mobile – +91-8181816477
Email – rudranshsinghrajpuorhit@gmail.com**

**Comment by Volmarg** [comment]
Hello,

Thank You for this information but I'm not fixing this. Reasons:
- the project is in mid of rewriting into api.
- as I wrote in many places the project is suppose to be hosted in locally closed network, since You are keeping Your data in it,
- the project is intended to be used by single person, so one instance = one user,
