### ISSUE TITLE
Error when accessing port 8002 in feature/2.0

### ISSUE THREAD

**Issue by Luk-7** [Volmarg/personal-management-system#147]
Hi, i read some of issues and found you have feature/2.0 that 5 ahead of main branches, but when i deploy using docker compose and accessing port it showing an error and the mailpit email me something about symphony, sorry i already undeploy, do you mind us step by step how to deploy feature/2,0 or is not stable yet.

**Comment by Volmarg** [comment]
Hello,

2.0 is not ready. I'll mergeit  to master and make a release once I'm done. For now You need to use `1.x`.

 It'll be couple of **months** before 2.0 is there.

The database structure won't change with 2.0 so updating will be pretty easy.

This will be front for 2.0 later then: https://github.com/Volmarg/personal-management-system-front

That should not really matter anyway, because I plan to make installation easy as well, with single docker-compose file.
