### ISSUE TITLE
laravel framework useability 

### ISSUE THREAD

**Issue by Shohan494** [Volmarg/personal-management-system#24]
Pretty impressive repo.. Found it nice foe personal use but I am a die hard laravel addict, any thoughts about how can I adopt this with it easily?

**Comment by Volmarg** [comment]
Last time when I worked with `Laravel` was like 1.5 years ago probably. From what I've seen in my old project on `Laravel` it was on `5.5.x` and now it seems like there is version `7.x` around.

Can't say what where and so on, but generaly based on my experience with `Laravel` from back then and when I switched to `Symfony` as actually for me `Laravel` was first framework and shortly after creating the project with it I went into `Symfony`.

- switching from `Laravel` to `Symfony` is generaly easy as plenty of core methods are just there, this is what I mean when You work with Laravel and got to start someting new with Symfony,
- I've long forgotten what mechanisms are there in Laravel for database ORM,


**So pretty much what do You need to have in mind for this in my opinion**
- You got to adapt the entities to Your `Laravel`, as `Symfony` is working with `Doctrine`, and I got no idea what is the core for database in `Laravel` nowadays,
- second You've got also to deal with the `Migrations` which are `Sqls` executed for database changes`
- same goes for the `Repositories` which contain sql **CRUD**, besides `Doctrine` uses `QueryBuilders` and so i use this mechnism in my Project, pretty much this will also need to be adapted in case when You are not using `Doctrine in `Laravel` version,
- Im pretty sure that You should not have problem with adding `webpack` into the `Laravel` since this is just used via console for compiling all the js files into one usable bundle, however You might need to reconfigure the main `config file for webpack` as if I remember correctly there are some paths added pointing to all the resources and the output files,
- templates, back then `laravel` used `Blades`. In symfony there is `Twig` so this will need to be rewriten from scratch unless You got some kind of importing mechnism nowadays but i doubt it, also You might need to change controllers a bit since You are going to use the blades now but I'm pretty sure that when I worked with `Blades` the params for rendering were also `(templateName, vairablesArray)`,
- In `symfony` im using `Route annotations`, no idea if this is supported in `Laravel` as back then I had no idea or never even tried to look for anything like this in `Laravel`,
- Symfony **does not** have the `middleware` now, it was present back then in 2x+ at least,
- I use `Fos bundle` for users, so if this package will not work with `Laravel` You will need to adjust any packages that You got and add the required fields,
- `configs(yamls)` - I got no idea how `Laravel` is handling config storage but if You got some other mechanisms there You will need to change and test alot with this because via yamls there are some dependencies configured, passwords encoding etc,
- some custom commands may not work for You. In Symfony we got `bin/console` for listing all the comands for example, and so I created some custom commands which I call via cron.

This is pretty much all that comes to my mind - I do realise that there might be some misspelling and so on, but I just write it `on fly` without fixing anything and so on, I hope that You can understand what I wrote. If someting is not clear then feel free to ask.

**Comment by Shohan494** [comment]
@Volmarg Thanks a lot honestly for your generous reply throughout your busy time, I am kinda busy too and surely will be back to read the whole response. Thought it's necessary to give you a reply.. Stay safe and code happy

**Comment by Volmarg** [comment]
I will close it for now - if You will have some questions then please reopen or make new issue.
