### ISSUE TITLE
Trying to get in touch with you regarding a security issue

### ISSUE THREAD

**Issue by huntr-helper** [Volmarg/personal-management-system#67]
Hi there,

I couldn't find a `SECURITY.md` in your repository and so am not sure how to best contact you privately to disclose the security issue.

Can you add a `SECURITY.md` file with your e-mail to your repository, so that I know who to contact? GitHub suggests that a [security policy](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) is the best way to make sure security issues are responsibly disclosed.

Once you've done that, please let me know so I can ping you the info.

Thanks! (cc @JamieSlome)

**Comment by Volmarg** [comment]
Hello,

You could provide me the info to `dwlodarczyk13@tlen.pl`.

The thing is that the project is slowly reaching the end (meaning that i got 99% of what i initially planned - ready), i still got few smaller things planned. So I'm not adding the `security.md` rather than that I will gladly take a look of any issue You got and add the ones i consider fatal / fast for late on.

**Comment by JamieSlome** [comment]
No worries - you should receive the reports via e-mail within the next hour!

Let me know if you have any questions!

**Comment by Volmarg** [comment]
Saw them all. 
Nothing big / important. I will skip them - still thx for information.

I consider this not important at all because:

https://volmarg.github.io/docs/summary/questions-and-answers
![image](https://user-images.githubusercontent.com/37488679/124789156-50235980-df4a-11eb-8c6c-665a0039188a.png)

This project is for private devices etc - should never be put online. So not adjusting this.
