### ISSUE TITLE
Unraid - Docker - Can't Connect?

### ISSUE THREAD

**Issue by evedoesaudiothings** [Volmarg/personal-management-system#69]
Hi,

I've followed the docker installation guide on here, have all the containers up and running from compose but I'm hitting 2 issues

1. The step where I enter the container and am supposed to call 'docker-first-run.sh' where is that file? 
2. The installer.php shows up but I have no idea how to connect to the running db? What is the exact information I need to plug in there? If I try the same thing with Docker on WSL I get to php installed but mysql isnt? Whereas when I'm trying on unraid, I just get an unspecific error page. 

What do I do?

**Comment by Volmarg** [comment]
Hello,

Today I can only answer **no1** (to tired to even understand no2).

If You downloaded release then it wasn't there because it was only in master. I added new release - You can download it.
This is the file: https://github.com/Volmarg/personal-management-system/blob/main/docker-first-run.sh

When You enter the `php-fpm` the file is directly in the `/application`. Just do `ls` You will see it.

**Comment by evedoesaudiothings** [comment]
Hey,

Thank you so much for pushing a new release <3 This worked perfectly. 

I haven't figured out how to upload files or anything yet but I really like this.

**Comment by Volmarg** [comment]
**2**

I don't get this. You are trying to get it working with docker?
You should not use the gui installer then but just call the `'docker-first-run.sh'` what error You see?

**Comment by Volmarg** [comment]
No feedback - closing.
