### ISSUE TITLE
Final talk and never will bothering you after that

### ISSUE THREAD

**Issue by amammad** [Volmarg/personal-management-system#74]
My dear, I worked hard for your repository and as you can see in my Video PoC in previous issue, There are several CSRF vulnerabilities in your very nice application and you should make CSRF token for each endpoint but only for login.

Can I ask you validate my reports on huntr.dev please?

they will remain hidden and unpublished until you submit a fix for them and also you can give White hackers like me A good motivation and help the open source community, be free and make a free decisions my dear.
Best regard,Amammad.

**Comment by Volmarg** [comment]
Hello,

Thank You for message but I’m not implementing CSRF tokens for each end points.

**Reasons / Explanation.**

Overall the CSRF token protection makes in general no sense in my project – that’s because the project should NEVER be accessible outside. If someone by any chance is putting his data outside of local network then **_this is not what the project was created for_**.

External data exposition should be handled by my other project created for just that purpose:
https://github.com/Volmarg/personal-management-system-io

Then again the project above is for **personal usage** only thus giving it to other ppl is a no.
Above mentioned tool, already has a fine set, of data protection.

I’m working on the other project where CSRF check for every end point makes sense because it might / most likely will be used for commercial purposes so naturally I want to avoid cases when backend route gets called from unauthorized source.

I’m open for safety matters but such as the one above as this has no right to exist in first place.

This is what has to be remembered here: The project goal is to having it in local network.

I know from other ppl that if they expose the project externally they **DO** filter the connections in local network so that is secure enough if they follow the: “Deny all”.

**Comment by amammad** [comment]
OK my dear I hope always you have a secure programming days :)
Best regards, Amammad.
